@baseUrl = http://localhost:8000
@urlPath = api

###
POST {{baseUrl}}/{{urlPath}}/chat/message
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "conversationId": "",
  "receiverId": "",
  "body": "",
  "gifUrl": "",
  "isRead": false,
  "selectedImage": ""
}

###
POST {{baseUrl}}/{{urlPath}}/chat/users
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "receiverId": ""
}

###
DELETE {{baseUrl}}/{{urlPath}}/chat/users
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "receiverId": ""
}
