@baseUrl = http://localhost:8000
@urlPath = api

###
POST {{baseUrl}}/{{urlPath}}/users/all
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "page": 1,
  "pageSize": 10
}

###
GET {{baseUrl}}/{{urlPath}}/users/<userId>
Content-Type: application/json
Accept: application/json
withCredentials: true

###
GET {{baseUrl}}/{{urlPath}}/users/suggestions
Content-Type: application/json
Accept: application/json
withCredentials: true

###
GET {{baseUrl}}/{{urlPath}}/user/search/<search-username-query>
Content-Type: application/json
Accept: application/json
withCredentials: true

###
GET {{baseUrl}}/{{urlPath}}/user/profile
Content-Type: application/json
Accept: application/json
withCredentials: true

###
GET {{baseUrl}}/{{urlPath}}/user/posts/<userId>
Content-Type: application/json
Accept: application/json
withCredentials: true

###
PUT {{baseUrl}}/{{urlPath}}/user/change-password
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "currentPaassword": "",
  "newPassword": "",
  "confirmPassword": ""
}
